### PR TITLE
Fix android volume issue

### PR DESCRIPTION
**Pull request by aelmadani**
Microphone volume is low in android web calls. I found 2 solutions:
https://github.com/datso/react-native-pjsip/issues/186
https://github.com/florindumitru/react-native-sip/issues/9

 I combined these two changes and tested mic audio. Big improvement.

### CODE REVIEW

**Review by c960657 — APPROVED** [review]
Excellent 👌

How did you determine that 3 is the right value? Trial and error?

**Comment by aelmadani** [comment]
> Excellent 👌
> 
> How did you determine that 3 is the right value? Trial and error?

2 did not improve volume. 3 combined with changing `mAudioManager` mode gave good results. I'm testing a new combination before merging.

**Comment by aelmadani** [comment]
The biggest improvement in voice volume is actually achieved by changing audioManager mode to `MODE_IN_COMMUNICATION`. So  I'm going back to the default `1.5` gain in for audioMedia.

**Review by c960657 — APPROVED** [review]
👍

**Pull request merged**
